### ISSUE TITLE
As user I expect that non-code is not counted

### ISSUE THREAD

**Issue by DanielRuf** [plantain-00/code-count#2]
#### Version(if relevant): 1.0.0
1.1.1
#### Code(if relevant):

```
// code here
```

#### Expected:
Comments are ignored
#### Actual:
Comments are counted

I guess this tool tries to reproduce what `cloc` already does.

**Comment by plantain-00** [comment]
I will count empty lines, but for comment lines, it varies considerably in various programming languages, and not in my use case.
